import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

export default async function generatePDF(bill) {
  const pdfDoc = await PDFDocument.create();

  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  const page = pdfDoc.addPage([595, 842]); // A4
  const { width, height } = page.getSize();

  const business = bill.business || {};
  const address = business.address || {};
  const contact = business.contact || {};

  let y;

  /* ================= HEADER BAR ================= */
 /* ================= HEADER BAR ================= */
page.drawRectangle({
  x: 0,
  y: height - 95,
  width,
  height: 95,
  color: rgb(0.12, 0.18, 0.35), // ✅ RESTORED ORIGINAL BLUE
});


  page.drawText(business.businessName || "Business Name", {
    x: 40,
    y: height - 45,
    size: 20,
    font: boldFont,
    color: rgb(1, 1, 1),
  });

  page.drawText(
    `${address.line1 || ""}, ${address.city || ""}, ${address.state || ""} - ${
      address.pincode || ""
    }`,
    {
      x: 40,
      y: height - 65,
      size: 10,
      font,
      color: rgb(1, 1, 1),
    }
  );

  page.drawText(
    `GST No: ${business.gstNumber || "N/A"}  |  Phone: ${contact.phone || "-"}`,
    {
      x: 40,
      y: height - 80,
      size: 10,
      font,
      color: rgb(1, 1, 1),
    }
  );

  page.drawText("TAX INVOICE", {
    x: width - 160,
    y: height - 55,
    size: 16,
    font: boldFont,
    color: rgb(1, 1, 1),
  });

  y = height - 125;

  /* ================= BILL INFO ================= */
  page.drawRectangle({
    x: 40,
    y: y - 40,
    width: width - 80,
    height: 40,
    color: rgb(0.95, 0.95, 0.95),
  });

  page.drawText(`Bill No: ${bill.billNo}`, {
    x: 50,
    y: y - 26,
    size: 11,
    font: boldFont,
  });

  page.drawText(`Date: ${new Date(bill.date).toDateString()}`, {
    x: width - 200,
    y: y - 26,
    size: 11,
    font: boldFont,
  });

  y -= 60;

  page.drawText(`Customer Name: ${bill.customerName}`, {
    x: 40,
    y,
    size: 12,
    font: boldFont,
  });

  y -= 25;

  /* ================= TABLE ================= */
  const colX = {
    sno: 50,
    particular: 100,
    qty: 320,
    rate: 380,
    amount: 460,
  };

  const rowHeight = 28;

  page.drawRectangle({
    x: 40,
    y: y - rowHeight,
    width: width - 80,
    height: rowHeight,
    color: rgb(0.85, 0.85, 0.85),
  });

  ["S.No", "Particular", "Qty", "Rate", "Amount"].forEach((t, i) => {
    const keys = ["sno", "particular", "qty", "rate", "amount"];
    page.drawText(t, {
      x: colX[keys[i]],
      y: y - 20,
      size: 11,
      font: boldFont,
    });
  });

  y -= rowHeight;

  bill.items.forEach((item, index) => {
    page.drawRectangle({
      x: 40,
      y: y - rowHeight,
      width: width - 80,
      height: rowHeight,
      borderWidth: 1,
      borderColor: rgb(0.8, 0.8, 0.8),
    });

    page.drawText(String(index + 1), {
      x: colX.sno,
      y: y - 20,
      size: 11,
      font,
    });

    page.drawText(item.particular, {
      x: colX.particular,
      y: y - 20,
      size: 11,
      font,
    });

    page.drawText(String(item.qty), {
      x: colX.qty,
      y: y - 20,
      size: 11,
      font,
    });

    page.drawText(String(item.rate), {
      x: colX.rate,
      y: y - 20,
      size: 11,
      font,
    });

    page.drawText(String(item.amount), {
      x: colX.amount,
      y: y - 20,
      size: 11,
      font,
    });

    y -= rowHeight;
  });

  y -= 30;

  /* ================= CALCULATIONS ================= */
  const gstRate = bill.gstPercentage || 18;
  const subTotal = bill.items.reduce(
    (sum, i) => sum + Number(i.amount),
    0
  );
  const gstAmount = (subTotal * gstRate) / 100;
  const grandTotal = subTotal + gstAmount;

  /* ================= TOTAL BREAKUP ================= */
  page.drawText(`Sub Total: Rs. ${subTotal.toFixed(2)}`, {
    x: width - 260,
    y,
    size: 11,
    font,
  });

  y -= 18;

  page.drawText(`GST (${gstRate}%): Rs. ${gstAmount.toFixed(2)}`, {
    x: width - 260,
    y,
    size: 11,
    font,
  });

  y -= 22;

  page.drawText(`Grand Total: Rs. ${grandTotal.toFixed(2)}`, {
    x: width - 260,
    y,
    size: 14,
    font: boldFont,
  });

  y -= 20;

  page.drawText(`Amount in Words: ${bill.amountInWords}`, {
    x: 40,
    y,
    size: 10,
    font,
  });

  /* ================= FOOTER ================= */
  y -= 50;

  page.drawText(`Generated By: ${bill.username || "System"}`, {
    x: 40,
    y,
    size: 10,
    font,
  });

  page.drawText("Authorized Signature", {
    x: width - 200,
    y,
    size: 10,
    font,
  });

  return await pdfDoc.save();
}
